### ISSUE TITLE
it's erro,why?

### ISSUE THREAD

**Issue by TheCryingGame** [Ridter/noPac#1]
i dont know why 
![image](https://user-images.githubusercontent.com/48227194/145803781-02130445-8663-441b-937e-cdc1e292709d.png)

**Comment by kosmosx2** [comment]
("('socket ssl wrapping error: [SSL: NO_CIPHERS_AVAILABLE] no ciphers available (_ssl.c:997)',)",)

i am getting this error too

**Comment by TryA9ain** [comment]
> ("('socket ssl wrapping error: [SSL: NO_CIPHERS_AVAILABLE] no ciphers available (_ssl.c:997)',)",)
> 
> i am getting this error too

this error too

**Comment by TheCryingGame** [comment]
emmm...
i am getting socket ssl wrapping error: [Errno 54] Connection reset by peer

**Comment by Ridter** [comment]
Try the new version, if there are still ssl errors, you can add **-use-ldap** to use ldap to connect.
