### ISSUE TITLE
STATUS_MORE_PROCESSING_REQUIRED({Still Busy} The specified I/O request packet (IRP) cannot be disposed of because the I/O operation is not complete.

### ISSUE THREAD

**Issue by archidote** [Ridter/noPac#12]
Hello, I got this error when I try to execute this command :

python3 noPac.py lgds.local/alex.henry:'123+aze' -dc-ip 192.168.130.101 -dc-host dc-ws16 -shell --impersonate root2 -use-ldap

target system : Windows Server 2016 (Build version : 14393.1884 )

Strange, because I have a smb share on this target lab, and ADDS/DNS rôles (linked to my lab domain)

Windows Defender does not flag nothing....

Lab configuration : 

dc.lgds.local (ws22) : 192.168.130.100
dc-ws16.lgds.local (ws16) : 192.168.130.101
kali linux : 192.168.130.128

![image](https://user-images.githubusercontent.com/38756128/173900027-16f26f17-b586-435c-9459-1771cd664e9e.png)

Have you got any idea ? 

Best regards,

**Comment by archidote** [comment]
[UPDATE]

I don't know if this update will help someone, but in case of ... 


Finally, I don't found the solution, But after a troublshooting session, I have detected that it's a was a DNS (Records) replication problem between my two AD : 
-WS22
-WS16

When I solve the replication problem, noPac was succefully executed on my target machine (ws16)

++

**Comment by barrett092** [comment]
I'm running into this same error.

**Comment by sec13b** [comment]
how you solve the replication problem?

**Comment by archidote** [comment]
> how you solve the replication problem?

wow, that's old ^^ 

dude, if I'm not being silly, I think I modified my /etc/resolv.conf file and specified the second dns (ws16) 

or maybe I had rebooted my DCs (I was in a lab)
