### ISSUE TITLE
Why "automatic bind not successful - invalidCredentials" error?

### ISSUE THREAD

**Issue by RENYONGTONG** [Ridter/noPac#4]
Hi Thanks for the upload, I tried different user but get same error.

PS C:\tools\NOPAC\noPac-main\noPac-main> python noPac.py contoso.com/user01:'P@ssw0rd' -dc-ip 192.168.200.100

automatic bind not successful - invalidCredentials

![image](https://user-images.githubusercontent.com/58537852/145934847-6ee08ab9-ae58-4930-827e-b7a29bee52d7.png)

**Comment by Ridter** [comment]
invalidCredentials !!
